FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGRiYWFzLW1hcmlhZGItYXBiCmRlc2NyaXB0aW9uOiBNYXJpYURC\
IGFzIGEgU2VydmljZQpiaW5kYWJsZTogVHJ1ZQphc3luYzogb3B0aW9uYWwKbWV0YWRhdGE6CiAg\
ZGlzcGxheU5hbWU6IExhZ29vbiBEQmFhUyAtIE1hcmlhREIgKEFQQikKICBkZXBlbmRlbmNpZXM6\
IFtdCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogTGFnb29uCiAgaW1hZ2VVcmw6ID4tCiAgICBodHRw\
czovL3d3dy5hbWF6ZWUuaW8vc2l0ZXMvZGVmYXVsdC9maWxlcy8yMDE4LTEwL2FtYXplZWlvLnBu\
ZwpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBUaGlzIGRlZmF1bHQg\
cGxhbiBjcmVhdGVzIGEgREIgdXNlciBhbmQgc2NoZW1hIChzYW1lIGFzIHByb2R1Y3Rpb24gcGxh\
bikKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFyYW1ldGVyczogW10KICAt\
IG5hbWU6IHByb2R1Y3Rpb24KICAgIGRlc2NyaXB0aW9uOiBUaGlzIGRlZmF1bHQgcGxhbiBjcmVh\
dGVzIGEgREIgdXNlciBhbmQgc2NoZW1hIGZvciBwcm9kdWN0aW9uIHNpdGVzCiAgICBmcmVlOiBU\
cnVlCiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6IFtdCiAgLSBuYW1lOiBzdGFnaW5n\
CiAgICBkZXNjcmlwdGlvbjogVGhpcyBkZWZhdWx0IHBsYW4gY3JlYXRlcyBhIERCIHVzZXIgYW5k\
IHNjaGVtYSBmb3Igc3RhZ2luZyBzaXRlcwogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9\
CiAgICBwYXJhbWV0ZXJzOiBbXQogIC0gbmFtZTogZGV2ZWxvcG1lbnQKICAgIGRlc2NyaXB0aW9u\
OiBUaGlzIGRlZmF1bHQgcGxhbiBjcmVhdGVzIGEgREIgdXNlciBhbmQgc2NoZW1hIGZvciBkZXZl\
bG9wbWVudCBzaXRlcwogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0\
ZXJzOiBbXQo="



COPY playbooks /opt/apb/actions
COPY . /opt/ansible/roles/dbaas-mariadb-apb
RUN chmod -R g=u /opt/{ansible,apb} \
 && yum -y install MySQL-python python-mysqldb mysql && yum clean all

#ENV BUNDLE_DEBUG=true

USER apb
